### PR TITLE
Fix n+1 queries on homepage

### PR DESCRIPTION
**Pull request by timhabermaas**
* Eager load authors of posts.
* Prevent querying crash_course_post multiple times by using slug for comparison.

### CODE REVIEW

**Comment by jfly** [comment]
Thanks for looking into this, @timhabermaas. Before we merge this, I was wondering about how you prevent these sorts of things in the first place. Do you know anything about https://github.com/flyerhzm/bullet?

**Comment by timhabermaas** [comment]
I know about `bullet` and it works pretty well. We probably should consider adding it.

**Comment by jfly** [comment]
Ok, I've createe https://github.com/cubing/worldcubeassociation.org/issues/358 to track adding bullet. Merging this up!

**Comment by timhabermaas** [comment]
For the record, before:

```
I, [2016-01-30T01:16:38.893119 #77430]  INFO -- : Started GET "/" for ::1 at 2016-01-30 01:16:38 +0100
D, [2016-01-30T01:16:38.899141 #77430] DEBUG -- :   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 169  ORDER BY `users`.`id` ASC LIMIT 1
I, [2016-01-30T01:16:38.899918 #77430]  INFO -- : Processing by PostsController#index as HTML
D, [2016-01-30T01:16:38.907818 #77430] DEBUG -- :   Post Load (0.3ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`world_readable` = 1  ORDER BY `posts`.`sticky` DESC, `posts`.`created_at` DESC LIMIT 30 OFFSET 0
D, [2016-01-30T01:16:38.909648 #77430] DEBUG -- :   Post Load (0.2ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1
D, [2016-01-30T01:16:38.909932 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.910708 #77430] DEBUG -- :   User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1
D, [2016-01-30T01:16:38.911230 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.911431 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.911821 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1  [["id", 159]]
D, [2016-01-30T01:16:38.912214 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.912418 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.913064 #77430] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 157 LIMIT 1
D, [2016-01-30T01:16:38.913553 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.913789 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.914382 #77430] DEBUG -- :   User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 158 LIMIT 1
D, [2016-01-30T01:16:38.914836 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.915040 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.915466 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 158 LIMIT 1  [["id", 158]]
D, [2016-01-30T01:16:38.915857 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.916050 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.916444 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 158 LIMIT 1  [["id", 158]]
D, [2016-01-30T01:16:38.916811 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.917026 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.917386 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 157 LIMIT 1  [["id", 157]]
D, [2016-01-30T01:16:38.917782 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.917971 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.918360 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1  [["id", 159]]
D, [2016-01-30T01:16:38.918756 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.918950 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.919652 #77430] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 160 LIMIT 1
D, [2016-01-30T01:16:38.920262 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.920571 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.921272 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 160 LIMIT 1  [["id", 160]]
D, [2016-01-30T01:16:38.921801 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.922039 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.922490 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 157 LIMIT 1  [["id", 157]]
D, [2016-01-30T01:16:38.922893 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.923086 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.923469 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 160 LIMIT 1  [["id", 160]]
D, [2016-01-30T01:16:38.923859 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.924076 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.924483 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 157 LIMIT 1  [["id", 157]]
D, [2016-01-30T01:16:38.924921 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.925124 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.925543 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1  [["id", 159]]
D, [2016-01-30T01:16:38.925964 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.926269 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.926656 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1  [["id", 159]]
D, [2016-01-30T01:16:38.927130 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.927383 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.928153 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1  [["id", 159]]
D, [2016-01-30T01:16:38.928740 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.928990 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.929438 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 160 LIMIT 1  [["id", 160]]
D, [2016-01-30T01:16:38.929883 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.930088 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.930490 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 160 LIMIT 1  [["id", 160]]
D, [2016-01-30T01:16:38.930916 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.931121 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.931516 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 158 LIMIT 1  [["id", 158]]
D, [2016-01-30T01:16:38.931903 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.932126 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`slug` = 'delegate-crash-course' LIMIT 1  [["slug", "delegate-crash-course"]]
D, [2016-01-30T01:16:38.932505 #77430] DEBUG -- :   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 159 LIMIT 1  [["id", 159]]
I, [2016-01-30T01:16:38.932774 #77430]  INFO -- :   Rendered posts/_post.html.erb (23.6ms)
I, [2016-01-30T01:16:38.932921 #77430]  INFO -- :   Rendered posts/index.html.erb within layouts/application (25.7ms)
D, [2016-01-30T01:16:39.196622 #77430] DEBUG -- :   Competition Load (0.4ms)  SELECT `Competitions`.* FROM `Competitions` INNER JOIN `competition_delegates` ON `Competitions`.`id` = `competition_delegates`.`competition_id` WHERE `competition_delegates`.`delegate_id` = 169 AND `Competitions`.`isConfirmed` = 0
D, [2016-01-30T01:16:39.197267 #77430] DEBUG -- :   Competition Load (0.3ms)  SELECT `Competitions`.* FROM `Competitions` INNER JOIN `competition_organizers` ON `Competitions`.`id` = `competition_organizers`.`competition_id` WHERE `competition_organizers`.`organizer_id` = 169 AND `Competitions`.`isConfirmed` = 0
D, [2016-01-30T01:16:39.198205 #77430] DEBUG -- :   User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` = 169
I, [2016-01-30T01:16:39.200617 #77430]  INFO -- :   Rendered shared/_user_avatar.html.erb (1.3ms)
I, [2016-01-30T01:16:39.201143 #77430]  INFO -- :   Rendered layouts/_navigation.html.erb (9.0ms)
I, [2016-01-30T01:16:39.202343 #77430]  INFO -- :   Rendered layouts/_flash.html.erb (0.2ms)
I, [2016-01-30T01:16:39.204025 #77430]  INFO -- :   Rendered layouts/_footer.html.erb (0.2ms)
I, [2016-01-30T01:16:39.204265 #77430]  INFO -- : Completed 200 OK in 304ms (Views: 300.7ms | ActiveRecord: 3.0ms)
```

After:
```
I, [2016-01-30T01:15:49.068258 #77371]  INFO -- : Started GET "/" for ::1 at 2016-01-30 01:15:49 +0100
D, [2016-01-30T01:15:49.074613 #77371] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 169  ORDER BY `users`.`id` ASC LIMIT 1
I, [2016-01-30T01:15:49.075398 #77371]  INFO -- : Processing by PostsController#index as HTML
D, [2016-01-30T01:15:49.084232 #77371] DEBUG -- :   Post Load (0.4ms)  SELECT  `posts`.* FROM `posts` WHERE `posts`.`world_readable` = 1  ORDER BY `posts`.`sticky` DESC, `posts`.`created_at` DESC LIMIT 30 OFFSET 0
D, [2016-01-30T01:15:49.086023 #77371] DEBUG -- :   User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (159, 157, 158, 160)
I, [2016-01-30T01:15:49.093783 #77371]  INFO -- :   Rendered posts/_post.html.erb (6.5ms)
I, [2016-01-30T01:15:49.093856 #77371]  INFO -- :   Rendered posts/index.html.erb within layouts/application (10.4ms)
D, [2016-01-30T01:15:49.326835 #77371] DEBUG -- :   Competition Load (0.4ms)  SELECT `Competitions`.* FROM `Competitions` INNER JOIN `competition_delegates` ON `Competitions`.`id` = `competition_delegates`.`competition_id` WHERE `competition_delegates`.`delegate_id` = 169 AND `Competitions`.`isConfirmed` = 0
D, [2016-01-30T01:15:49.327417 #77371] DEBUG -- :   Competition Load (0.3ms)  SELECT `Competitions`.* FROM `Competitions` INNER JOIN `competition_organizers` ON `Competitions`.`id` = `competition_organizers`.`competition_id` WHERE `competition_organizers`.`organizer_id` = 169 AND `Competitions`.`isConfirmed` = 0
D, [2016-01-30T01:15:49.328265 #77371] DEBUG -- :   User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` = 169
I, [2016-01-30T01:15:49.330368 #77371]  INFO -- :   Rendered shared/_user_avatar.html.erb (1.1ms)
I, [2016-01-30T01:15:49.330835 #77371]  INFO -- :   Rendered layouts/_navigation.html.erb (8.5ms)
I, [2016-01-30T01:15:49.331616 #77371]  INFO -- :   Rendered layouts/_flash.html.erb (0.1ms)
I, [2016-01-30T01:15:49.332469 #77371]  INFO -- :   Rendered layouts/_footer.html.erb (0.1ms)
I, [2016-01-30T01:15:49.332667 #77371]  INFO -- : Completed 200 OK in 257ms (Views: 255.0ms | ActiveRecord: 1.7ms)
```

**Comment by jfly** [comment]
How much can we trust the timing logs at the end?

```
I, [2016-01-30T01:16:39.204265 #77430]  INFO -- : Completed 200 OK in 304ms (Views: 300.7ms | ActiveRecord: 3.0ms)
```

```
I, [2016-01-30T01:15:49.332667 #77371]  INFO -- : Completed 200 OK in 257ms (Views: 255.0ms | ActiveRecord: 1.7ms)
  Delete branch
```

**Comment by timhabermaas** [comment]
Not much since I used development mode. The same page using production mode (after this patch): `Completed 200 OK in 13ms (Views: 11.4ms | ActiveRecord: 0.7ms)`

**Pull request merged**
