### PR TITLE
Re-initialize *all* tooltips after ajax.

### PR DESCRIPTION
**Pull request by jfly**
Right now, the tooltips @pedrosino added for the checkboxes aren't being initialized after ajax.

@pedrosino, could you take a look at this?

### CODE REVIEW

**Comment by jonatanklosko** [comment]
I think we can make use of the font-awesome icon helper (changing the icons' size via CSS to something like 15px):
```ruby
<%= icon("check-circle", title: "Results are posted!", data: { toggle: "tooltip" }) %>
```
Then we can just put the data-placement in the JS initialization as before.

When you look at the WCA now, you can see that because competition names have a different length, the 'check' icon isn't aligned and it doesn't look very well. Maybe we should place the flag before the country name, and the 'check' icon before competition name?

**Comment by pedrosino** [comment]
I'm confused here. I just tried the page and all the tooltips seem to work after a few new loads...

Jeremy said the one I added doesn't work, but this PR doesn't touch them :confused:

**Comment by jonatanklosko** [comment]
@pedrosino the tooltips aren't re-initialized and I guess what you see is the title attribute. I've just checked and it's a bit similar to a tooltip in my browser indeed.

**Comment by pedrosino** [comment]
Ooooh, I see. It's not a pretty baloon as the tooltip, and appears on the bottom of the icon instead of the top.

I understand the PR now. Jeremy is making the other tooltips the same as mine, and changed the javascript to reload all of them.

As for Jonatan's comment, I'm not sure it would work. The competitions names would not be aligned because some will have the icon and some won't. Maybe we should always put the icon there and only make it visible if results are up.

**Comment by pedrosino** [comment]
```
<span class="glyphicon glyphicon-ok-sign" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-container="body" title="Results are posted!" style="<%= competition.results_posted_at ? '' : 'visibility:hidden' %>"></span>
```
Screenshot:
icons

**Comment by jfly** [comment]
@jonatanklosko, I would rather keep the tooltip placement information in the html, because that's how we've been handling this everywhere else in the website. If I move it back to the script tag at the bottom of `WcaOnRails/app/views/competitions/_index_table.html.erb`, then maybe someday later we'll add a tooltip where we want the position to be right, and we'll have to change the js again.

I've moved the icons around as per @pedrosino's recommendation. I agree it looks better... on big screens. Check it out:

image

image

An alternative that I like is to actually get rid of the hourglass and replace them with the checkbox. I think this is pretty clear: if the results for a competition have been uploaded, then the competition is definitely over =)

2016-05-06_10 33 23_1875x510_kaladin


image

**Comment by jonatanklosko** [comment]
I like this idea a lot, LGTM!

**Comment by jfly** [comment]
Merged and deployed =)

**Pull request merged**
