### PR TITLE
Fix N+1 query when editing User's status

### PR DESCRIPTION
**Pull request by viroulep**
This one I could fix :)

I got the popup when trying to change the delegate status from a user (board->senior).

### CODE REVIEW

**Comment by jonatanklosko** [comment]
I'm wondering whether this won't cause bullet to detect unused `includes` calls for other actions using `user_to_edit`. Did you check it?

**Comment by larspetrus** [comment]
Not every N+1 query is a problem.

Is there a way to tell Bullet to whitelist the ones we don't want to change?

**Comment by jonatanklosko** [comment]
[Here](https://github.com/flyerhzm/bullet#whitelist) it is. I think it can be also applied to  #617.

**Comment by viroulep** [comment]
@jonatanklosko  Erf you're right, the log does say that it's unused when sending a PATCH for instance.

@larspetrus, ok. Just to be sure I got it right: the idea is to show a warning when we do something like 100 requests of 1 "thing" instead of 1 request of 100 "things", but we don't care when it's simply one additional request for an associated object to one "thing". Right?

**Comment by larspetrus** [comment]
Yeah, when N is low we don't care (as much). Specifically, when N = 1, doing the include doesn't help at all.

There is also the case when you only _sometimes_ need the N queries. Maybe this is an example of that.

**Comment by viroulep** [comment]
Ok :)
Then this PR is no good and we should go by your suggestion.

**Pull request closed without merging**
