### PR TITLE
Add a tooltip with additional time information on hourglass hover.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fiexs #470. I came up with nice idea, screenshots are worth a thousand words, look!
- in progress:
image
- upcoming
image
- passed
image

### CODE REVIEW

**Comment by jfly** [comment]
@FatBoyXPC, can you take this one on, as #470 was your idea? =) =)

**Comment by FatBoyXPC** [comment]
It looks like the screenshot shows upcoming competitions have the same icon as past competitions?

**Comment by jonatanklosko** [comment]
Oh, sorry, I've copied and pasted it. Thanks for vigilance.

**Comment by FatBoyXPC** [comment]
LGTM! :shipit:

**Pull request merged**
