### PR TITLE
Fix models to account for marked_for_destruction?

### LINKED ISSUE #883: poll.rb is ignoring `marked_for_destruction`
See discussion [here](https://github.com/cubing/worldcubeassociation.org/pull/759/files/092c6c899303fd543fc8b55597e4fb8ebc2c16fe#r78271394) and [here](http://homeonrails.com/2012/10/validating-nested-associations-in-rails/).

Adding the following test to `poll_spec.rb` fails:

```ruby
    it "cannot remove poll options on a confirmed poll" do
      poll = FactoryGirl.create :poll
      FactoryGirl.create(:poll_option, poll_id: poll.id)
      FactoryGirl.create(:poll_option, poll_id: poll.id)
      poll.confirmed = true
      expect(poll).to be_valid
    
      poll.poll_options[0].mark_for_destruction
      poll.poll_options[1].mark_for_destruction
      expect(poll).to be_invalid
    end
```

### LINKED ISSUE #884: team.rb is ignoring team_members that have been marked for deletion
See https://github.com/cubing/worldcubeassociation.org/blob/54194f897fad85bb5eac393cd4ae46e53f1a5650/WcaOnRails/app/models/team.rb#L10, where we look at all the `team_members` without first checking to see if they've been "marked for deletion".

This is similar to #883.

### LINKED ISSUE #885: registration.rb is ignoring registration_events that have been marked for deletion
https://github.com/cubing/worldcubeassociation.org/blob/54194f897fad85bb5eac393cd4ae46e53f1a5650/WcaOnRails/app/models/registration.rb#L35-L37 doesn't check to see if a `registration_events` has been marked for deletion first.

This is similar to #883.

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #883 fixes #884 fixes #885

### CODE REVIEW

**Comment by pedrosino** [comment]
See https://github.com/cubing/worldcubeassociation.org/issues/883#issuecomment-246683307

**Comment by jonatanklosko** [comment]
LGTM

**Comment by jonatanklosko** [comment]
LGTM, let @jfly look at this though as he created all these issues =)

**Comment by larspetrus** [comment]
Something like this should be the right way:

`has_many :registration_events, -> { where(marked_for_destruction: false) }`

**Comment by jonatanklosko** [comment]
@larspetrus It's not a real column but just a method.

**Comment by larspetrus** [comment]
Huh. This stuff seems icky... I'd look pretty hard for ways to not deal with `marked_for_destruction?`, and if that's not feasible maybe try something like this:

    has_many :_registration_events, class_name: 'RegistrationEvent'
    def self.registration_events
      self._registration_events.reject(&:marked_for_destruction?)
    end

Expecting all future programmers to "remember" to never use `registration_events` directly is not much of an option.

**Comment by jonatanklosko** [comment]
I think that overriding association is error prone, especially as we'd return an array instead of a relation. At least we can make it a separate method, but I'm not sure what's the best way of solving this.

**Comment by jfly** [comment]
@larspetrus, I totally agree. This `marked_for_destruction` stuff is one of the icky-est things I've seen in rails-land. From googling around, it seems like people do "just remember" if the association they're dealing with can be `marked_for_destruction`.

Your idea to change the relevant methods to ignore child objects that are `marked_for_destruction` is tempting. However, my gut feeling here is that the default Rails behavior was a conscious decision. I may be wrong about this, but I fear that there may be unintended side effects to that change, beyond what @jonatanklosko has already mentioned. Perhaps @timhabermaas can provide some insight into how he has dealt with this sort of stuff in the past?

**Comment by jfly** [comment]
That all said, while I do not love this solution, it is easy to find ocurrences of `marked_for_destruction` in our codebase. I think we should merge this up as is, and either continue the discussion here or start a new issue for improving this.

LGTM!

**Comment by timhabermaas** [comment]
> Perhaps @timhabermaas can provide some insight into how he has dealt with this sort of stuff in the past?

Assuming the `marked_for_destruction?` pain exists because of `accepts_nested_attributes_for`: I've tried to stay away from `accepts_nested_attributes_for` for quite some time now. While the coupling between forms and the database (ActiveRecord) is already pretty high in Rails land - `accepts_nested_attributes_for` is on an entirely different level...
In the past I've either:
* Sent AJAX requests (e.g. `DELETE /registrations/23/events/12` or `DELETE /registration_events/1234`) when the user removes a checkbox/clicks "Delete". This makes the backend code super simple, it's usually just a `DELETE ... WHERE id = ?`. Note: You can't wrap removing multiple entries in a transaction anymore, but this is rarely an issue.
* or implemented the diffing myself by adding a hidden field with all the join table ids to the form. It's pretty easy to mess up, though.

Does this help?

**Comment by jfly** [comment]
@timhabermaas, thanks for the feedback. I like the simplicity of AJAX here, but it seems like the UX might be a bit schizophrenic if you fire the ajax at the time the user clicks an X... our users have been trained to treat our forms as something they can throw away just by closing their tabs, it might be surprising to find that some database writes actually *did* occur, despite them not saving the form.

Does that seem like a valid concern? Do you have any advice for ensuring a good user experience with this?

**Comment by timhabermaas** [comment]
@jfly Yeah, this seems like a valid concern. Removing the "Submit" button and having some kind of feedback (e.g. "You're no longer registered for 3x3x3") probably helps. As long as the user has an easy way to fix his mistakes this probably works fine. GMail kinda works like that: deleting an email is easily reverted.

If you want to keep the current workflow you can also save all actions the user made so far in a list (`[{action: 'remove_event', id: 23}]`), provide him with a textual representation of all his changes ("removed from 3x3x3 event", "added to 4x4x4 event") and send that list to the server once the user clicks "Submit". This has the added benefit of a trivial "Undo" implementation, but codingwise it's definitely more involved. Buzzword: CQRS.

**Comment by jonatanklosko** [comment]
Seems like you messed the commits somehow.

**Comment by pedrosino** [comment]
I'll go ahead and merge this for now, until (if we ever) we come up with a better solution.

**Pull request merged**
