### PR TITLE
Requesites for Persons Fixes/Changes Applications

### PR DESCRIPTION
**Pull request by SAuroux**
File to be linked in the delegate crash course

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Just to note somewhere: apart from the pre-commit errors,  it seems that you ran into #450.

**Comment by SAuroux** [comment]
I'm completely lost there, sorry. How could adding a binary file to a
folder cause any issues at all?

2016-05-20 11:42 GMT+02:00 Jonatan Kłosko <notifications@github.com>:

**Comment by jonatanklosko** [comment]
The issue I linked is a test bug (that should be finally fixed as it occured again) and should no longer fail when we re-run travis.
I don't know what those pre-commit errors are about, because I cannot look into the pdf at the moment. Isn't it about trailing white characters or something?

**Comment by SAuroux** [comment]
So...is there some way to just add the file now? I would like to update the
crash course depending on it
Am 20.05.2016 12:37 schrieb "Jonatan Kłosko" <notifications@github.com>:

**Comment by jfly** [comment]
Closing in favor of #649

**Comment by jfly** [comment]
Just deployed #649. See https://www.worldcubeassociation.org/files/requisites_for_fixes_updates.pdf.

**Pull request closed without merging**
