### PR TITLE
Fix pop up on the competition's edit page

### LINKED ISSUE #790: Admin competition view asks if I want to leave
(Sorry, couldn't think of a better title)

When I'm at competition/edit/admin, even if I don't change anything it shows a pop-up asking if I really want to leave if I try to close the window.
I thought it was just with me, but @Luis-J-Ianez reported the same behaviour. It didn't happen some time ago (not sure how long).

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #790. See [this comment](https://github.com/cubing/worldcubeassociation.org/issues/790#issuecomment-237180810) for detailed description.

### CODE REVIEW

**Comment by pedrosino** [comment]
LGTM

**Comment by jfly** [comment]
Wait! Before you merge this, can you explain why this is happening? The comment here https://github.com/cubing/worldcubeassociation.org/issues/790#issuecomment-237180810 doesn't quite explain it to me.

**Comment by pedrosino** [comment]
I believe once the page was loaded, the checkbox was triggered, thus telling the browser that you changed something, which led to the "are you sure you want to leave?" message.

**Comment by jonatanklosko** [comment]
Triggering the check box change isn't the reason,
setting `external_website` input to disabled is what causes the pop up to appear (it's treated as input change I guess).
Why do we disable the field? -> Because if the `generate_website` is checked we don't need `external_website` to be sent with the form params (we just don't care about the url).
Why can we let the field be enabled? -> Because we have a callback that ensures that `external_website` is set to `nil` if we use WCA as competition's website. So whatever competition's url will be sent with the params, it will be discarded if `generate_website` is set to true.
I hope that makes sense for you =)

**Comment by jfly** [comment]
Ahh, I think I see. Would a better fix be to ignore disabled inputs when checking if the form is dirty?

**Comment by jfly** [comment]
After disucssing offline, it doesn't seem worth it to fork/monkey patch the are you sure jquery library.

LGTM!

**Pull request merged**
