### PR TITLE
Update redcarpet to prevent memory leak

### PR DESCRIPTION
**Pull request by timhabermaas**
See https://github.com/vmg/redcarpet/pull/516

### CODE REVIEW

**Comment by timhabermaas** [comment]
cc @jfly

**Comment by jfly** [comment]
Wow, what a fun article to read!

Is there any reason to update `Gemfile` as well as `Gemfile.lock`?

**Comment by timhabermaas** [comment]
> Is there any reason to update `Gemfile` as well as `Gemfile.lock`?

A reason for setting the gem versions in the `Gemfile` is to prevent `bundle update` from breaking the app, so I just started doing it. Shall I remove it?

Btw. I changed the `>= 3.3.3` to `~> 3.3`.

**Comment by jfly** [comment]
Ohh, I guess with your change if we were to theoretically add a new gem that requires an older version of redcarpet, we'd get a nice error, rather than `bundle update` happily downgrading our `redcarpet` to make everyone happy?

**Pull request merged**
