### PR TITLE
Don't tab on datetime_picker hide.

### LINKED ISSUE #409: Clicking away from a date input focuses the next input, which can cause an incredibly annoying page scroll
Say you're editing a competition's registration close datetime field like this:

2016-02-29_20 11 09_892x703_kaladin

Then, instead of selecting a registration close, you scroll up to the top of the page, with the intention of editing the venue details:

2016-02-29_20 11 35_892x703_kaladin

However, once you click on the venue details, that causes a `dp.hide` event to fire, which triggers the code @pedrosino added in #398 . This actually focuses the next field after competition registration close, which is Remarks, which causes a huge page scroll back to the bottom of the page:

2016-02-29_20 11 19_892x703_kaladin

@pedrosino, can you take a look at this? I plan to comment out https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/javascripts/application.js#L84-L90 until this is resolved.

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #409

### CODE REVIEW

**Comment by jfly** [comment]
I'm not at a computer right now, but doesn't #409 apply to date pickers? My understanding of the code is that the same crazy scrolling will happen with them as well.

**Comment by jfly** [comment]
Here's the behavior I see with this change.

First start editing competition start date:

2016-03-01_08 39 22_816x703_kaladin


Then scroll down to remarks and attempt to click on it:

2016-03-01_08 39 34_816x703_kaladin

Rage that you're now editing the competition end date:

2016-03-01_08 39 37_816x703_kaladin

How about *only* doing this autofocus next for the first datepicker (NOT datetimepicker) in a range?

**Comment by pedrosino** [comment]
I think not, because once you click the date, the picker will hide and it will tab to the next input.

**Comment by jfly** [comment]
LGTM, :ship: it!!

**Pull request merged**
