### PR TITLE
Very long venue names don't appear on a new line anymore when listing competitions

### LINKED ISSUE #503: Very long venue name
image

### PR DESCRIPTION
**Pull request by coder13**
fixes #503.

Screenshot: 
selection_080

### CODE REVIEW

**Comment by jfly** [comment]
Is that the before screenshot, or the after? Please include both and label them =)

**Comment by jfly** [comment]
Oh, nevermind! Just noticed there's a screenshot on #503.

**Comment by jfly** [comment]
Did you verify that things still look good on mobile?

**Comment by coder13** [comment]
I made sure that things looked good on mobile. It should all be good.

**Comment by jfly** [comment]
LGTM!

**Pull request merged**
