### PR TITLE
Fixing the date check for competitions too close

### PR DESCRIPTION
**Pull request by pedrosino**
Added .abs to the "days_until" thing. Competitions which were before the current one have a negativa value for this, so it was always <= 30.

### CODE REVIEW

**Comment by jfly** [comment]
Looks good to me, although I do like Tim's suggestion to move this logic into the model! Can we do that?

**Comment by pedrosino** [comment]
I don't see the need to have a method which is a copy of another, just with the values changed...
We do a filter in the query to exclude those competitions which are too far away in time and space. The list contains all the "warning" and "danger" cases, but they are not black and white. The red background is just a visual sign of a competition that _may_ be too close.

**Comment by timhabermaas** [comment]
It was just a suggestion to improve encapsulation. Feel free to do whatever you want, it's not bad code. And the following discussion is not worth having, so :+1: for merging.

> I don't see the need to have a method which is a copy of another, just with the values changed...

You're referring to `Competition#nearby_competitions`, right? Duplicating logic between db queries and app code is common, mainly for performance reasons (`WHERE` is faster than `Array#select`). Not much you can do about that. _Not_ adding a method is still duplicating logic, though. There's just no name associated with it.

> We'd query the DB twice to retrieve almost the same information.

The code I had in mind was:

```ruby
class Competition
  def dangerously_close_to?(c)
    days_until = (c.start_date - self.start_date).to_i
    self.kilometers_to(c) <= NEARBY_DISTANCE_KM_DANGER && days_until.abs < NEARBY_DAYS_DANGER
  end
end
```

If I'm not missing anything there would be no additional db queries.

**Comment by pedrosino** [comment]
Yeah, Jeremy explained it to me. I'll try to do it later today.

**Comment by pedrosino** [comment]
Done here: https://github.com/pedrosino/worldcubeassociation.org/commit/7030c477e28c0dfa46231e2aa284dffba1bfafb2

**Comment by jfly** [comment]
On further thought, do we prefer "18 days earlier/later" or "18 days before/after"?

**Comment by jfly** [comment]
Merged and pushed to production!

**Comment by pedrosino** [comment]
I prefer before and after...
I can ask the board members if you wish

**Comment by jfly** [comment]
Nah, if you have a preference, let's stick with it.

**Pull request merged**
