### PR TITLE
Add support for markdown tables, along with a custom renderer that

### PR DESCRIPTION
**Pull request by jfly**
adds class "table" so bootstrap will style them.

### CODE REVIEW

**Comment by pedrosino** [comment]
That looks very cool, but apparently tests failed...

How would usage look like?

**Comment by jfly** [comment]
See example post here: https://staging.worldcubeassociation.org/posts/test

**Comment by jfly** [comment]
Looks like the test failed due to #639, I've restarted the test for now.

**Comment by jonatanklosko** [comment]
I'd make a separate helper file for markdown things because application's one is becoming pretty long.
Apart from that this LGTM!

**Pull request merged**
