### PR TITLE
Move schema monkey patch to initializer

### PR DESCRIPTION
**Pull request by timhabermaas**
@jfly That's what I meant.

btw. I tried regenerating the schema from scratch (because I wasn't sure how the exact formatting of the auto-generated code is), but I can't get past the `no_drupal` migration because of some missing table. Might be worth fixing some time.

### CODE REVIEW

**Comment by jfly** [comment]
LGTM!

Yeah, regenerating the schema from scratch is not gonna work. I bootstrapped things by running `rake db:schema:dump` on a mysql instance with a full database dump. My reading led my to believe that there is no expectation that you are actually able to run all the migrations in a project from scratch (one of the reasons you check in schema.rb in the first place).

A more immediate goal might be to get `rake db:schema:dump` working. That monkey patch you just moved around relies upon some edits to schema.rb that I had to make by hand, and have to reintroduce every time we do a db migration. Just run `rake db:schema:dump; git diff` to see what I mean.

**Comment by jfly** [comment]
Whoops! Forgot to actually merge it.

**Comment by timhabermaas** [comment]
> My reading led my to believe that there is no expectation that you are actually able to run all the migrations in a project from scratch

I'm not sure about the expectation Rails has, but it's extremely helpful in practice to rerun the migrations from scratch. I haven't worked on a Rails project where people didn't manage to get the migrations and the schema.rb out of sync (happens quite easily when switching between branches without rolling transactions back).

In order to get a valid migration sequence when being forced to use an existing database you can always add one initial migration which is basically just a dump of the current database.

> and have to reintroduce every time we do a db migration.

Argh, that's unfortunate. It might be solvable by monkey patching the schema generation - but I'm not too keen on diving into the Rails internals.

After typing all that: What about switching the schema format to SQL (`config.active_record.schema_format = :sql`)? I _believe_ this should fix all the issues we currently have.

**Comment by timhabermaas** [comment]
There's a drawback to using the `sql` format, though: We can't easily switch between Sqlite and MySQL anymore, but I think we should use the same database for production and development/tests anyway. (I got bitten by case sensitivity issues with MySQL vs PostgreSQL once...)

**Comment by jfly** [comment]
I might be being dense, but did you say what the benefits are of of being able to run the migrations from scratch?

Ah, `config.active_record.schema_format = :sql` does sound like it would solve a lot of our problems. Since everything is in Vagrant, we can introduce mysql without causing trouble for our developers, which is nice. Would things get complicated if we ever want to move to say, PostgreSQL? What about getting travis-ci working without sqlite?

As you said, using the same db everywhere would be a good thing. [This](https://github.com/cubing/worldcubeassociation.org/commit/3ea44abf2db0dca36d1dee7abe535dfa5560b23e) is an example of a weird mysql-ism that I could not reproduce in sqlite.

**Comment by timhabermaas** [comment]
> I might be being dense, but did you say what the benefits are of of being able to run the migrations from scratch?

No, I didn't get into details.

The migrations provide a better single place of truth than the schema. It comes down to: the events leading to the current state provide more information than the current state alone. The current state (`schema.rb`) usually gets corrupted by either:

* merge conflicts
* careless developers who commit schema changes without a accompanying migration (this _will_ happen)

If you could execute the migration from scratch these could simply be fixed by: `rake db:drop db:create db:migrate`. In our case we're left with either manually comparing migrations with the schema.rb or going back a few commits, copying the valid schema and reapplying the migrations. It's not the end of the world, just slightly inconvenient.

> Would things get complicated if we ever want to move to say, PostgreSQL?

We'd need to translate the schema + fix any raw SQL statements. When using ActiveRecord's query interface it's usually a drop-in-replacement. I doubt we'd need more than a day to make the switch.

**Comment by jfly** [comment]
That makes a lot of sense, thanks.

I'm all for going to SQL, so long as we keep travis working somehow. Are you up for making this change?

**Comment by timhabermaas** [comment]
> Are you up for making this change?

Yes, I'm working on it: #173

**Pull request merged**
