### PR TITLE
Use gsub(/ /, '$20') instead of URI.encode.

### LINKED ISSUE #726: Discussion_url not being set
It works great locally and at staging, but for some reason it's not working at production.
I'll change to gsub(/ /, '$20') instead of URI.encode...

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #726

### CODE REVIEW

**Comment by larspetrus** [comment]
Weird. We probably have to worry about encoding other characters than spaces?

Not that that should stop an emergency deploy, if that's what's needed.

**Comment by jonatanklosko** [comment]
Such a replacement itn's sufficient as there are other special characters which must be escaped.

**Comment by jonatanklosko** [comment]
Actually current code doesn't work for me at staging.

**Comment by jonatanklosko** [comment]
Check [this](http://stackoverflow.com/a/19059183) out.

**Comment by pedrosino** [comment]
irb(main):003:0> ERB::Util.url_encode('Uberlândia Open 2016')
=> "Uberl%C3%A2ndia%20Open%202016"
irb(main):004:0> CGI::escape('Uberlândia Open 2015')
=> "Uberl%C3%A2ndia+Open+2015"

Both seem to work good with Google...

**Comment by jonatanklosko** [comment]
This wasn't the way to go, the problem was simpler. See [this comment](https://github.com/cubing/worldcubeassociation.org/issues/726#event-704248802).

**Pull request closed without merging**
