### PR TITLE
Remove extra spaces around trimmed solves.

### PR DESCRIPTION
**Pull request by jfly**
See @Laura-O's comment here: https://github.com/cubing/worldcubeassociation.org/issues/510#issuecomment-2117939050.

Before:

image

After:

image

### CODE REVIEW

**Comment by jonatanklosko** [comment]
It would be nice to change [this](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/stylesheets/wca.scss#L168) to  ```text-align: center;```. It would look cleaner certainly.
Before:
image

After:
image

**Comment by jfly** [comment]
In your example, all the times are 2 digits long. I don't think text-align center is nice when you have times of different length. What's unclean about `text-align: right`?

**Comment by jonatanklosko** [comment]
I think it's cleaner even if the times have different lengths, look:
image

image

Even at the moment times are not really right aligned because some of them in the same column have right bracket. In my opinion it's kinda messy.

**Comment by jfly** [comment]
Ah, I see. Ok, crazy idea. What do you think about this:

image

You'll see that all the times line up nicely now. I achieved this by *always* inserting a ( and a ) with opacity 0, and changing the opacity to 1 if this solve is trimmed.

**Comment by pedrosino** [comment]
I prefer Jonatan's last version.

**Comment by Laura-O** [comment]
If I understand it right, Jeremy's solution would mean that all results are in brackets when you c&p them, right?
The solution definitely looks better, but that would be quite inconvenient.

**Comment by jfly** [comment]
Actually, web browsers seem to ignore the css ::before and ::after content when copy pasting. See it for real here: https://staging.worldcubeassociation.org/competitions/EastJapanBigCubes2015

**Comment by Laura-O** [comment]
Ok, good. It definitely looks much better!

**Pull request merged**
