### PR TITLE
Make WCA Website Comments email subject more descriptive

### LINKED ISSUE #819: Representative subject for mails sent through form to notifications@worldcubeassociation.org
Presently all have the same subject: "WCA Website Comments".  Could you add something more representative, like at least the sender's name? "WCA Website Comments by Peter Jackson"

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #819.

### CODE REVIEW

**Comment by pedrosino** [comment]
This solves the issue for now, until we come up with a better system for the contact thing.

**Comment by larspetrus** [comment]
This obviously works and is a big improvement. Still, if the same person sends several comments, they will be grouped in the same thread by mail clients.

So could we (easily!) put in a date or timestamp or something else?

If not, LGTM

**Comment by jonatanklosko** [comment]
@larspetrus Is this fine =) ?
```ruby
2.3.0 :027 > name = "Someone"
 => "Someone" 
2.3.0 :028 > DateTime.now.strftime("WCA Website Comments by #{name} on %A, %d %b %Y at %r")
 => "WCA Website Comments by Someone on Saturday, 20 Aug 2016 at 12:36:54 AM" 
2.3.0 :029 >
```

**Comment by larspetrus** [comment]
I'd prefer `DateTime.now.strftime("WCA Website Comments by #{name} on %d %b %Y at %R")`, because

- The weekday is redundant and makes it very long
- Only Americans use AM/PM

Does that make sense?

**Comment by jonatanklosko** [comment]
Yeah, this is definitely better =)

**Comment by larspetrus** [comment]
LGTM, again

**Pull request merged**
