### PR TITLE
Update to the latest version of rubocop

### PR DESCRIPTION
**Pull request by jfly**
This should suppress this warning we've been seeing:

```
~/worldcubeassociation.org/WcaOnRails @production> (cd
/home/cubing/worldcubeassociation.org/WcaOnRails; RACK_ENV=production
bin/rake work:schedule)
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.0-compliant syntax, but you are running 2.3.1.
warning: please see
https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

### CODE REVIEW

**Comment by viroulep** [comment]
Works great :)
However how is this a rubocop update if the version of rubocop's gem is not modified?

**Comment by jonatanklosko** [comment]
@viroulep I thought the same, the reason is that we specifyexact rubocop  version in the [Gemfile](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/Gemfile#L78). We should be consistent and either don't store any version constraints or add it to every gem (I'm up for the first solution as Gemfile.lock keeps track of the installed versions).

**Comment by jfly** [comment]
I suspect the reason why we put a version number in our `Gemfile` was because of this text from https://github.com/bbatsov/rubocop#installation:

> RuboCop's development is moving at a very rapid pace and there are often backward-incompatible changes between minor releases (since we haven't reached version 1.0 yet). To prevent an unwanted RuboCop update you might want to use a conservative version locking in your Gemfile:

That said, I agree that we should not be putting version numbers in our Gemfile, and instead let Gemfile.lock take care of stuff.

Upgrading to the latest version of rubocop caused a lot of little failures, which I've fixed. The biggest change was that the `Style/FrozenStringLiteralComment` cop has been enabled by default, which I could have disabled, but I decided to add the "# frozen_string_literal: true" comment to all our files.

**Comment by jonatanklosko** [comment]
LGTM!

**Pull request merged**
