### PR TITLE
Clean countries

### LINKED ISSUE #779: Remove unnecessary countries fields
Countries have three columns that don't have reasonable values so it doesn't make sense to keep them: `zoom`, `longitude`, `latitude`.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #779.

### CODE REVIEW

**Comment by larspetrus** [comment]
Shouldn't `structure.sql` be in this PR?

That `id` == `name` still looks crazy, but I that's a separate issue.

**Comment by jonatanklosko** [comment]
`structure.sql` is here, it's last file of the diff =)

**Comment by larspetrus** [comment]
Duh. I was searching for ".rb"...

**Comment by jfly** [comment]
LGTM! Have you checked if this will break any PHP code?

**Comment by jonatanklosko** [comment]
I've just searched for `longitude`, `latitude`, `zoom` and haven't found any usage of the Countries' ones =)

**Pull request merged**
