### PR TITLE
Fix typo in function call

### PR DESCRIPTION
**Pull request by viroulep**
Fix a typo in the `can_see_admin_competitions?` call, which is causing the crash @SAuroux has reported.

### CODE REVIEW

**Comment by viroulep** [comment]
The amin page simply doesn't without this, so I'll go ahead and consider this critical and merge it right away ;)

**Comment by pedrosino** [comment]
Oh, was it me who did this? :(

**Comment by viroulep** [comment]
Yep, git blame designated you :p
The fun part is that if you look at the file history you'll see that you
got it right in the first place, and refractored it wrong.

Le 1 sept. 2016 12:12 PM, "Pedro Santos" <notifications@github.com> a
écrit :

**Comment by pedrosino** [comment]
Ah, I made so many commits there :P Weird that travis or rubocop didn't notice the non-existing method.

**Pull request merged**
