### PR TITLE
Overriding bootstrap's table striped colors.

### PR DESCRIPTION
**Pull request by pedrosino**
I think the default gray looks way too light, barely noticeable.

### CODE REVIEW

**Comment by jfly** [comment]
Cool! Could you include a screenshot?

@lgarron , @FatBoyXPC could you chime in here on the actual choice of color?

**Comment by pedrosino** [comment]
@lgarron Also see https://github.com/cubing/worldcubeassociation.org/issues/261#issuecomment-163074131

**Comment by jfly** [comment]
Ok, nobody seems to have any objections to this. I plan to push this live on Wednesday.

**Comment by pedrosino** [comment]
Nice! :+1:

**Comment by jfly** [comment]
Merged!

**Comment by pedrosino** [comment]
Yay!

**Pull request merged**
