### PR TITLE
For Francois, RIP

### PR DESCRIPTION
**Pull request by jfly**
Pictures for posterity:

image

The rose links to Francois's profile page:

image

### CODE REVIEW

**Comment by jfly** [comment]
This is currently on https://staging.worldcubeassociation.org/.

@lgarron made the lovely rose.

**Comment by lgarron** [comment]
Note to selves: this doesn't properly take into account the media queries to resize the icon for mobile.

**Comment by lgarron** [comment]
We should figure out when we want to remove this again. I think about one week is reasonable; ho about removing on Monday?

**Comment by jfly** [comment]
I think we should remove this whenever Ron and Philippe decide to make the post unsticky. @viroulep, did you have a plan for when that should be?

**Comment by viroulep** [comment]
No, I'll check with Ron.

**Comment by pedrosino** [comment]
We have un-sticked the announcement, so please go ahead and remove the rose.

**Pull request merged**
